# Generated by Django 4.2 on 2024-08-27 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='groups',
            field=models.ManyToManyField(related_name='author_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='author',
            name='user_permissions',
            field=models.ManyToManyField(related_name='author_permissions', to='auth.permission'),
        ),
    ]
