# Generated by Django 4.2 on 2024-08-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0003_remove_publication_author_publication_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='date_publication',
            field=models.DateField(auto_created=True),
        ),
    ]
