# Generated by Django 4.2 on 2024-08-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0004_alter_publication_date_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='date_publication',
            field=models.DateField(auto_now_add=True),
        ),
    ]
